### ISSUE TITLE
宝塔的防火墙貌似没用

### ISSUE THREAD

**Issue by coldeve** [pch18-docker/baota#21]
虽然自带打开了禁ping，照样ping的了服务器，并且设置端口是否通过也不影响服务器实际端口是否通过

**Comment by coldeve** [comment]
![image](https://user-images.githubusercontent.com/24355466/59268798-12c34380-8c80-11e9-8c08-5465c5eafd99.png)
我想关闭禁ping,就出现这个图标，刷新下网页照样禁ping是打开的

**Comment by pch18** [comment]
您需要关闭宿主机上的防火墙的icmp。
因为宝塔面板在容器中运行，您关闭的是只容器中的ping应答。

您检测的ping是宿主机应答的，并没有发送给宝塔面板。所以不会生效。
