### ISSUE TITLE
Docker 安装宝塔的用处

### ISSUE THREAD

**Issue by hb0730** [pch18-docker/baota#22]
请问一下，用Docker安装宝塔的作用，如果使用Docker安装宝塔，会不会影响宝塔的其他作用，或者说是否推荐直接使用Docker，而非宝塔，感谢！

**Comment by pch18** [comment]
安装面板后再安装php，mysql等非常费事，需要数小时才能完全安装，
使用docker镜像，可以针对需要的组件下载后立马就能部署使用。

宝塔面板对系统底层修改较多，一般只能在纯净的centos上安装。
安装后几乎不能完全卸载，如需卸载建议重装系统。
在docker上安装宝塔，可以很干净的卸载，重装。
而且对 macos 支持也很好。

目前没有发现在docker上安装宝塔会有什么影响，如果有请提出来，我会修复。
不是太推荐直接使用docker部署nginx，php，mysql等。配置，管理都很繁琐。
