### ISSUE TITLE
ssh默认账号密码是多少?

### ISSUE THREAD

**Issue by qq471754603** [pch18-docker/baota#23]
ssh默认账号密码是多少?

**Comment by pch18** [comment]
openssh 默认有密码么？我不是太清楚。
openshh 配置后没有进行配置密码的操作。
您可以尝试使用 `passwd` 来修改密码

**Comment by pch18** [comment]
刚刚尝试了一下，在面板里面操作 ssh 需要输入账号密码。
最近项目工期紧，过段时间会解决这个问题，使得安装后ssh可以直接操作，不用输入账号密码。

**Comment by pch18** [comment]
已经修复，您试试。宝塔中可以直接连接ssh。
默认ssh应该是证书登陆的，没有设置密码
