### ISSUE TITLE
安装好后，在宝塔软件商店点击一键部署就会卡死。一直显示正在获取列表 ...

### ISSUE THREAD

**Issue by playm3u8** [pch18-docker/baota#30]
安装好后，在宝塔软件商店点击一键部署就会卡死。一直显示正在获取列表 ... ，之后在访问软件商店就会一直显示正在获取列表... 重新安装也无法解决。
![QQ截图20190711142444](https://user-images.githubusercontent.com/42953966/61027033-a99e2f80-a3e7-11e9-81be-aa46d49542d8.jpg)

**Comment by pch18** [comment]
请检查联网是否正常,
尝试使用首页的修复宝塔面板工具.
刷新浏览器缓存后重试.
我这里不能复现此问题,应该属于个别情况.
