### ISSUE TITLE
服务器一般为40G,镜像以及文件超过40G,线上无法使用

### ISSUE THREAD

**Issue by qq471754603** [pch18-docker/baota#31]
服务器一般为40G,镜像以及文件超过40G,线上无法使用

**Comment by qq471754603** [comment]
![a](https://user-images.githubusercontent.com/23146592/61194705-d4dd9300-a6f5-11e9-8240-05fd7639a3ed.png)

**Comment by qq471754603** [comment]
这是清除过的,运行几天服务器直接当了

**Comment by qq471754603** [comment]
给公司搭的,打电话过来我一看,吓得我半夜三更,把docker镜像删了,在服务器主机重装了个环境

**Comment by pch18** [comment]
部署完,镜像文件运行环境大概只有5g左右吧.
是什么文件占空间?数据库么?还是网站的图片?
宿主机直接装环境,超过主机硬盘大小也照样宕机啊.
和用不用docker无关吧.

**Comment by pch18** [comment]
提问和使用docker的宝塔镜像无关,
先关闭issue,如果和使用docker的宝塔有关
请说明是什么文件占用空间,
到时将再次打开issue
