### ISSUE TITLE
 the next day on the third day, bt panel can't use

### ISSUE THREAD

**Issue by eremiter** [pch18-docker/baota#35]
Found not stable,  the next day on the third day, bt panel can't use, just install memcached,Redis, mysql, nginx, PHP

**Comment by pch18** [comment]
Please check if the server is out of memory, the memory is too small will cause the program to crash, it is recommended that the memory is above 4g.
I have been using it in the production environment for 2 years and it has been very stable.
If you can, please post the error message for better optimization.

**Comment by eremiter** [comment]
# free -h
total        used        free      shared  buff/cache   available
Mem:            15G        3.0G        9.5G        486M        3.1G         11G
Swap:          8.0G          0B        8.0G
======================
It has a lot of memory. It needs to restart bt in two days,
Otherwise, sorry, program exception, the page you requested was interrupted due to an exception

**Comment by eremiter** [comment]
[root@8abc3dfhost wwwroot]# cat  /www/server/panel/logs/error.log | tail -n 100
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/lib/python2.7/site-packages/flask_session/sessions.py", line 535, in save_session
    session_id=store_id).first()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3228, in first
    ret = list(self[0:1])
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
    return list(res)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3330, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3352, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 3345, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
    self._assert_active()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 282, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
2019-08-29 11:42:47 [34] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  post_fork: <function post_fork at 0x7f2649acc500>
  pythonpath: None
  syslog: False
  syslog_facility: user
  enable_stdio_inheritance: False
  worker_class: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
  ssl_version: 3
  cert_reqs: 0
  suppress_ragged_eofs: True
  when_ready: <function when_ready at 0x7f2649acc230>
  pre_fork: <function pre_fork at 0x7f2649acc398>
  preload_app: True
  workers: 1
  keepalive: 60
  accesslog: /www/server/panel/logs/access.log
  pidfile: /www/server/panel/logs/panel.pid
  worker_tmp_dir: None
  group: 0
  graceful_timeout: 0
  spew: False
  proc_name: None
  umask: 0
  on_reload: <function on_reload at 0x7f2649acc0c8>
  post_worker_init: <function post_worker_init at 0x7f2649acc668>
  pre_exec: <function pre_exec at 0x7f2649accaa0>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f2649ad11b8>
  config: runconfig.py
  logconfig: None
  check_config: False
  do_handshake_on_connect: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f2649accc08>
  post_request: <function post_request at 0x7f2649acccf8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f2649acc7d0>
  ca_certs: None
  threads: 3
  max_requests: 0
  chdir: /www/server/panel
  daemon: True
  user: 0
  limit_request_line: 4094
  access_log_format: %(h) -  %(t)s - %(u)s - %(s)s %(H)s
  certfile: None
  worker_exit: <function worker_exit at 0x7f2649acce60>
  paste: None
  default_proc_name: runserver:app
  errorlog: /www/server/panel/logs/error.log
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x7f2649acc938>
  loglevel: debug
  bind: ['0.0.0.0:8888']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f2649ad1050>
  timeout: 7200
  on_starting: <function on_starting at 0x7f2649ac4ed8>
  debug: False
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 512

**Comment by eremiter** [comment]
Command used：
docker run -tid --name baota -p 80:80 -p 443:443 -p 8888:8888 -p 888:888 --privileged=true --restart always -v ~/wwwroot:/www/wwwroot pch18/baota

**Comment by jimphei** [comment]
请问怎么进入容器，ssh的密码时多少

**Comment by pch18** [comment]
Please add the following parameters when running the container
` --shm-size=1g `

**Comment by pch18** [comment]
> 请问怎么进入容器，ssh的密码时多少

没密码，证书登陆，或者从宿主机用如下命令登陆
`docker exec -ti baota bash`
